version: '3.8'

volumes:
  postgres_data:
  static_volume:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build: .
    restart: always
    volumes:
      - static_volume:/code/static/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - static_volume:/code/static/
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - web
