version: '3.8'

volumes:
  postgres_data:
  static_volume:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build: .
    restart: always
    volumes:
      - static_volume:/code/static
    command: sh -c "python manage.py flush --no-input &&
             python manage.py migrate && 
             python manage.py loaddata fixtures.json && 
             python manage.py collectstatic --noinput && 
             gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static_volume:/code/static
    ports:
      - "80:80"
    depends_on:
      - web
